// <auto-generated />
using System;
using Biine.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Biine.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306143855_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Biine.API.Models.Interaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decision")
                        .HasColumnType("text");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Interactions");
                });

            modelBuilder.Entity("Biine.API.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CookingTime")
                        .HasColumnType("integer");

                    b.Property<string>("Cuisine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("IngredientsEn")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("IngredientsSv")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("InstructionsEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstructionsSv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonaTextEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonaTextSv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CookingTime = 25,
                            Cuisine = "Italian",
                            Difficulty = "Medium",
                            ImageUrl = "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800",
                            IngredientsEn = "[{\"name\":\"Pasta\",\"amount\":\"400 g\"},{\"name\":\"Eggs\",\"amount\":\"4\"},{\"name\":\"Pancetta\",\"amount\":\"150 g\"},{\"name\":\"Parmesan\",\"amount\":\"80 g\"},{\"name\":\"Black pepper\",\"amount\":\"to taste\"}]",
                            IngredientsSv = "[{\"namn\":\"Pasta\",\"mängd\":\"400 g\"},{\"namn\":\"Ägg\",\"mängd\":\"4 st\"},{\"namn\":\"Pancetta\",\"mängd\":\"150 g\"},{\"namn\":\"Parmesanost\",\"mängd\":\"80 g\"},{\"namn\":\"Svartpeppar\",\"mängd\":\"efter smak\"}]",
                            InstructionsEn = "1. Cook pasta al dente.\n2. Fry pancetta until crispy.\n3. Mix eggs and grated parmesan in a bowl.\n4. Toss hot pasta with pancetta off the heat.\n5. Pour egg mixture and stir quickly. Season with black pepper.",
                            InstructionsSv = "1. Koka pasta al dente.\n2. Stek pancetta knaprig.\n3. Blanda ägg och riven parmesan i en skål.\n4. Blanda den varma pastan med pancettan av värmen.\n5. Häll äggblandningen och rör snabbt. Krydda med svartpeppar.",
                            Name = "Carbonara",
                            PersonaTextEn = "I'm creamy, comforting, and unforgiving to cheaters. Roman born, hearts broken. Tagliatelle is my love language — and yes, I judge if you add cream.",
                            PersonaTextSv = "Jag är krämig, trygg och förlåter inte fuskare. Född i Rom, krossar hjärtan. Tagliatelle är mitt kärleksspråk — ja, jag dömer dig om du tillsätter grädde.",
                            Tags = new[] { "Pasta", "Cheesy", "Roman", "Quick" }
                        },
                        new
                        {
                            Id = 2,
                            CookingTime = 35,
                            Cuisine = "Mexican",
                            Difficulty = "Medium",
                            ImageUrl = "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800",
                            IngredientsEn = "[{\"name\":\"Pork\",\"amount\":\"500 g\"},{\"name\":\"Pineapple\",\"amount\":\"1/2\"},{\"name\":\"Chili peppers\",\"amount\":\"3\"},{\"name\":\"Tortillas\",\"amount\":\"8\"},{\"name\":\"Cilantro\",\"amount\":\"1 bunch\"}]",
                            IngredientsSv = "[{\"namn\":\"Fläskkött\",\"mängd\":\"500 g\"},{\"namn\":\"Ananas\",\"mängd\":\"1/2\"},{\"namn\":\"Chilepeppar\",\"mängd\":\"3 st\"},{\"namn\":\"Tortillas\",\"mängd\":\"8 st\"},{\"namn\":\"Koriander\",\"mängd\":\"1 knippe\"}]",
                            InstructionsEn = "1. Marinate pork in chili, achiote, and pineapple juice for 2 hours.\n2. Grill meat on high heat until caramelized.\n3. Slice thinly.\n4. Serve in warm tortillas with fresh pineapple and cilantro.",
                            InstructionsSv = "1. Marinera fläsket i chili, achiote och ananassaft i 2 timmar.\n2. Grilla köttet på hög värme tills karamelliserat.\n3. Skär i tunna skivor.\n4. Servera i varma tortillas med färsk ananas och koriander.",
                            Name = "Tacos al Pastor",
                            PersonaTextEn = "Looking for someone who can handle heat. I'm sweet, spicy, and pineapple'd. Best enjoyed standing up, watching the sunset. No quitters.",
                            PersonaTextSv = "Söker någon som tål värme. Jag är söt, kryddig och har ananas. Bäst njuten stående i solnedgången. Inga vekling.",
                            Tags = new[] { "Tacos", "Spicy", "Pineapple", "Street Food" }
                        },
                        new
                        {
                            Id = 3,
                            CookingTime = 20,
                            Cuisine = "Thai",
                            Difficulty = "Easy",
                            ImageUrl = "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800",
                            IngredientsEn = "[{\"name\":\"Rice noodles\",\"amount\":\"200 g\"},{\"name\":\"Shrimp\",\"amount\":\"200 g\"},{\"name\":\"Eggs\",\"amount\":\"2\"},{\"name\":\"Peanuts\",\"amount\":\"50 g\"},{\"name\":\"Fish sauce\",\"amount\":\"3 tbsp\"},{\"name\":\"Tamarind\",\"amount\":\"2 tbsp\"}]",
                            IngredientsSv = "[{\"namn\":\"Risnudlar\",\"mängd\":\"200 g\"},{\"namn\":\"Räkor\",\"mängd\":\"200 g\"},{\"namn\":\"Ägg\",\"mängd\":\"2 st\"},{\"namn\":\"Jordnötter\",\"mängd\":\"50 g\"},{\"namn\":\"Fisksås\",\"mängd\":\"3 msk\"},{\"namn\":\"Tamarind\",\"mängd\":\"2 msk\"}]",
                            InstructionsEn = "1. Soak noodles in warm water 15 min.\n2. Stir-fry shrimp in wok, set aside.\n3. Scramble eggs in wok.\n4. Add noodles, fish sauce, tamarind.\n5. Return shrimp. Top with peanuts and lime.",
                            InstructionsSv = "1. Blötlägg nudlarna i varmt vatten 15 min.\n2. Stek räkor i wok, lägg åt sidan.\n3. Vispa ägg i woken.\n4. Tillsätt nudlar, fisksås, tamarind.\n5. Lägg tillbaka räkorna. Toppa med jordnötter och lime.",
                            Name = "Pad Thai",
                            PersonaTextEn = "I'm that friend who's always balanced — sweet, sour, tangy, and a little sassy. Peanuts are my love language. Will ruin other Thai for you forever.",
                            PersonaTextSv = "Jag är den vännen som alltid är balanserad — söt, sur, syrlig och lite fräck. Jordnötter är mitt kärleksspråk. Förstör all annan Thai för dig för evigt.",
                            Tags = new[] { "Noodles", "Peanuts", "Tangy", "Quick" }
                        },
                        new
                        {
                            Id = 4,
                            CookingTime = 40,
                            Cuisine = "Indian",
                            Difficulty = "Medium",
                            ImageUrl = "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800",
                            IngredientsEn = "[{\"name\":\"Chicken breast\",\"amount\":\"600 g\"},{\"name\":\"Crushed tomatoes\",\"amount\":\"400 g\"},{\"name\":\"Cream\",\"amount\":\"200 ml\"},{\"name\":\"Butter\",\"amount\":\"3 tbsp\"},{\"name\":\"Garam masala\",\"amount\":\"2 tsp\"},{\"name\":\"Ginger\",\"amount\":\"1 tbsp\"}]",
                            IngredientsSv = "[{\"namn\":\"Kycklingfilé\",\"mängd\":\"600 g\"},{\"namn\":\"Krossade tomater\",\"mängd\":\"400 g\"},{\"namn\":\"Grädde\",\"mängd\":\"200 ml\"},{\"namn\":\"Smör\",\"mängd\":\"3 msk\"},{\"namn\":\"Garam masala\",\"mängd\":\"2 tsk\"},{\"namn\":\"Ingefära\",\"mängd\":\"1 msk\"}]",
                            InstructionsEn = "1. Marinate chicken in yoghurt and spices 30 min.\n2. Grill or pan-fry chicken.\n3. Sauté onion, ginger, garlic in butter.\n4. Add tomatoes and spices, simmer 10 min.\n5. Add cream and chicken. Simmer 10 min.",
                            InstructionsSv = "1. Marinera kyckling i yoghurt och kryddor 30 min.\n2. Grilla eller stek kyckling.\n3. Fräs lök, ingefära, vitlök i smör.\n4. Tillsätt tomater och kryddor, koka 10 min.\n5. Tillsätt grädde och kyckling. Låt puttra 10 min.",
                            Name = "Butter Chicken",
                            PersonaTextEn = "Rich, velvety, and not afraid of commitment. I'm mild but can go spicy if you earn it. Garam masala? More like full-body aroma. Come with naan, stay forever.",
                            PersonaTextSv = "Rik, sammetsmjuk och inte rädd för åtaganden. Jag är mild men kan bli het om du förtjänar det. Kom med naan, stanna för alltid.",
                            Tags = new[] { "Curry", "Creamy", "Mild", "Comfort" }
                        },
                        new
                        {
                            Id = 5,
                            CookingTime = 60,
                            Cuisine = "Japanese",
                            Difficulty = "Hard",
                            ImageUrl = "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=800",
                            IngredientsEn = "[{\"name\":\"Sushi rice\",\"amount\":\"300 g\"},{\"name\":\"Nori sheets\",\"amount\":\"4\"},{\"name\":\"Salmon\",\"amount\":\"200 g\"},{\"name\":\"Avocado\",\"amount\":\"1\"},{\"name\":\"Rice vinegar\",\"amount\":\"3 tbsp\"},{\"name\":\"Wasabi\",\"amount\":\"to taste\"}]",
                            IngredientsSv = "[{\"namn\":\"Sushiris\",\"mängd\":\"300 g\"},{\"namn\":\"Nori-alger\",\"mängd\":\"4 ark\"},{\"namn\":\"Lax\",\"mängd\":\"200 g\"},{\"namn\":\"Avokado\",\"mängd\":\"1 st\"},{\"namn\":\"Risvinäger\",\"mängd\":\"3 msk\"},{\"namn\":\"Wasabi\",\"mängd\":\"efter smak\"}]",
                            InstructionsEn = "1. Cook rice and mix with rice vinegar.\n2. Place nori on bamboo mat.\n3. Spread rice evenly.\n4. Place filling along the edge.\n5. Roll tight and cut into pieces.",
                            InstructionsSv = "1. Koka riset och blanda med risvinäger.\n2. Lägg norin på bambumatten.\n3. Bred ut riset jämnt.\n4. Lägg fyllning längs kanten.\n5. Rulla tight och skär i bitar.",
                            Name = "Sushi Roll",
                            PersonaTextEn = "Elegant, precise, and a little mysterious. I'm cold on the outside but warm inside. Wasabi is just my sense of humor. Serious about freshness, casual about vibes.",
                            PersonaTextSv = "Elegant, precis och lite mystisk. Kall utanpå men varm inuti. Wasabi är bara mitt sinne för humor. Seriös om fräschhet, avslappnad om stämningen.",
                            Tags = new[] { "Rice", "Sushi", "Fresh", "Elegant" }
                        },
                        new
                        {
                            Id = 6,
                            CookingTime = 20,
                            Cuisine = "American",
                            Difficulty = "Easy",
                            ImageUrl = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800",
                            IngredientsEn = "[{\"name\":\"Ground beef\",\"amount\":\"500 g\"},{\"name\":\"Cheddar\",\"amount\":\"4 slices\"},{\"name\":\"Brioche buns\",\"amount\":\"4\"},{\"name\":\"Lettuce\",\"amount\":\"4 leaves\"},{\"name\":\"Tomato\",\"amount\":\"1\"},{\"name\":\"Pickles\",\"amount\":\"4 slices\"}]",
                            IngredientsSv = "[{\"namn\":\"Nötfärs\",\"mängd\":\"500 g\"},{\"namn\":\"Cheddarost\",\"mängd\":\"4 skivor\"},{\"namn\":\"Briochebröd\",\"mängd\":\"4 st\"},{\"namn\":\"Sallad\",\"mängd\":\"4 blad\"},{\"namn\":\"Tomat\",\"mängd\":\"1 st\"},{\"namn\":\"Gurka\",\"mängd\":\"4 skivor\"}]",
                            InstructionsEn = "1. Form 4 patties from ground beef. Season generously.\n2. Grill on high heat 3-4 min per side.\n3. Add cheese in the last minute.\n4. Lightly toast the buns.\n5. Build the burger with all toppings.",
                            InstructionsSv = "1. Forma 4 biffar av nötfärsen. Krydda generöst.\n2. Grilla på hög värme 3-4 min per sida.\n3. Lägg ost på sista minuten.\n4. Rosta brödet lätt.\n5. Bygg burgaren med alla tillbehör.",
                            Name = "Burger",
                            PersonaTextEn = "Classic, no drama. I'm the whole package — patty, cheese, pickle, drama. Best with fries on the side and no questions asked. Thick, juicy, reliable.",
                            PersonaTextSv = "Klassisk, ingen drama. Jag är hela paketet — biff, ost, pickles, drama. Bäst med pommes och inga frågor. Tjock, saftig, pålitlig.",
                            Tags = new[] { "Beef", "Cheesy", "Classic", "BBQ" }
                        },
                        new
                        {
                            Id = 7,
                            CookingTime = 180,
                            Cuisine = "Vietnamese",
                            Difficulty = "Hard",
                            ImageUrl = "https://images.unsplash.com/photo-1614333626528-04b3de0bdb4e?w=800",
                            IngredientsEn = "[{\"name\":\"Beef bones\",\"amount\":\"1 kg\"},{\"name\":\"Rice noodles\",\"amount\":\"300 g\"},{\"name\":\"Star anise\",\"amount\":\"4\"},{\"name\":\"Cinnamon\",\"amount\":\"1 stick\"},{\"name\":\"Fish sauce\",\"amount\":\"4 tbsp\"},{\"name\":\"Fresh herbs\",\"amount\":\"1 bunch\"}]",
                            IngredientsSv = "[{\"namn\":\"Nötben\",\"mängd\":\"1 kg\"},{\"namn\":\"Risnudlar\",\"mängd\":\"300 g\"},{\"namn\":\"Stjärnanis\",\"mängd\":\"4 st\"},{\"namn\":\"Kanel\",\"mängd\":\"1 pinne\"},{\"namn\":\"Fisksås\",\"mängd\":\"4 msk\"},{\"namn\":\"Färska örter\",\"mängd\":\"1 knippe\"}]",
                            InstructionsEn = "1. Dry roast spices in a pot.\n2. Simmer bones with spices for 6-8 hours.\n3. Strain the broth.\n4. Cook the noodles.\n5. Serve noodles in hot broth with fresh herbs, bean sprouts, and lime.",
                            InstructionsSv = "1. Rosta kryddorna torrt i en gryta.\n2. Koka benen med kryddor i 6-8 timmar.\n3. Sila buljongen.\n4. Koka nudlarna.\n5. Servera nudlar i het buljong med färska örter, böngroddar och lime.",
                            Name = "Pho",
                            PersonaTextEn = "Complex, aromatic, and worth the wait. I take 8 hours to make and 10 minutes to fall in love with. Herbs are my personality. Comfort in a bowl.",
                            PersonaTextSv = "Komplex, aromatisk och värd väntan. Tar 8 timmar att laga och 10 minuter att förälska sig i. Örter är min personlighet. Tröst i en skål.",
                            Tags = new[] { "Soup", "Aromatic", "Herbs", "Noodles" }
                        },
                        new
                        {
                            Id = 8,
                            CookingTime = 30,
                            Cuisine = "Greek",
                            Difficulty = "Easy",
                            ImageUrl = "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800",
                            IngredientsEn = "[{\"name\":\"Chicken thighs\",\"amount\":\"600 g\"},{\"name\":\"Pita\",\"amount\":\"4\"},{\"name\":\"Tzatziki\",\"amount\":\"200 g\"},{\"name\":\"Tomato\",\"amount\":\"2\"},{\"name\":\"Red onion\",\"amount\":\"1\"},{\"name\":\"Paprika\",\"amount\":\"1 tsp\"}]",
                            IngredientsSv = "[{\"namn\":\"Kycklinglår\",\"mängd\":\"600 g\"},{\"namn\":\"Pita\",\"mängd\":\"4 st\"},{\"namn\":\"Tzatziki\",\"mängd\":\"200 g\"},{\"namn\":\"Tomat\",\"mängd\":\"2 st\"},{\"namn\":\"Rödlök\",\"mängd\":\"1 st\"},{\"namn\":\"Paprika\",\"mängd\":\"1 tsk\"}]",
                            InstructionsEn = "1. Marinate chicken in olive oil, garlic, paprika, oregano.\n2. Grill on high heat until cooked through.\n3. Warm the pita.\n4. Slice meat into strips.\n5. Serve in pita with tzatziki, tomato, and onion.",
                            InstructionsSv = "1. Marinera kyckling i olivolja, vitlök, paprika, oregano.\n2. Grilla på hög värme tills genomstekt.\n3. Värm pitan.\n4. Skär köttet i remsor.\n5. Servera i pitan med tzatziki, tomat och lök.",
                            Name = "Gyros",
                            PersonaTextEn = "Mediterranean charm with tzatziki swagger. I'm stacked, seasoned, and served with warmth. Pita not required but recommended. Feta is my love language.",
                            PersonaTextSv = "Medelhavscharme med tzatziki-swagger. Jag är välkryddad och serveras med värme. Pita rekommenderas. Feta är mitt kärleksspråk.",
                            Tags = new[] { "Pita", "Tzatziki", "Mediterranean", "Grilled" }
                        },
                        new
                        {
                            Id = 9,
                            CookingTime = 25,
                            Cuisine = "Italian",
                            Difficulty = "Easy",
                            ImageUrl = "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800",
                            IngredientsEn = "[{\"name\":\"Pizza dough\",\"amount\":\"300 g\"},{\"name\":\"Crushed tomatoes\",\"amount\":\"150 g\"},{\"name\":\"Mozzarella\",\"amount\":\"200 g\"},{\"name\":\"Basil\",\"amount\":\"1 bunch\"},{\"name\":\"Olive oil\",\"amount\":\"2 tbsp\"}]",
                            IngredientsSv = "[{\"namn\":\"Pizzadeg\",\"mängd\":\"300 g\"},{\"namn\":\"Krossade tomater\",\"mängd\":\"150 g\"},{\"namn\":\"Mozzarella\",\"mängd\":\"200 g\"},{\"namn\":\"Basilika\",\"mängd\":\"1 knippe\"},{\"namn\":\"Olivolja\",\"mängd\":\"2 msk\"}]",
                            InstructionsEn = "1. Preheat oven to 250°C.\n2. Roll dough thinly.\n3. Spread tomato sauce.\n4. Add torn mozzarella.\n5. Bake 8-10 min. Top with fresh basil.",
                            InstructionsSv = "1. Värm ugnen till 250°C.\n2. Kavla ut degen tunt.\n3. Bred tomatsås.\n4. Lägg på mozzarella i bitar.\n5. Grädda 8-10 min. Toppa med färsk basilika.",
                            Name = "Pizza Margherita",
                            PersonaTextEn = "Simple, iconic, and will never let you down. I'm red, white, green, and clean. Naples taught me less is more.",
                            PersonaTextSv = "Enkel, ikonisk och sviker aldrig. Jag är röd, vit, grön och ren. Neapel lärde mig att mindre är mer.",
                            Tags = new[] { "Pizza", "Tomato", "Basil", "Classic" }
                        },
                        new
                        {
                            Id = 10,
                            CookingTime = 120,
                            Cuisine = "Japanese",
                            Difficulty = "Hard",
                            ImageUrl = "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800",
                            IngredientsEn = "[{\"name\":\"Pork bones\",\"amount\":\"500 g\"},{\"name\":\"Ramen noodles\",\"amount\":\"300 g\"},{\"name\":\"Soy sauce\",\"amount\":\"4 tbsp\"},{\"name\":\"Miso paste\",\"amount\":\"2 tbsp\"},{\"name\":\"Eggs\",\"amount\":\"4\"},{\"name\":\"Nori\",\"amount\":\"4 sheets\"}]",
                            IngredientsSv = "[{\"namn\":\"Fläskben\",\"mängd\":\"500 g\"},{\"namn\":\"Ramennudlar\",\"mängd\":\"300 g\"},{\"namn\":\"Sojasamn\",\"mängd\":\"4 msk\"},{\"namn\":\"Miso\",\"mängd\":\"2 msk\"},{\"namn\":\"Ägg\",\"mängd\":\"4 st\"},{\"namn\":\"Nori\",\"mängd\":\"4 ark\"}]",
                            InstructionsEn = "1. Simmer bones in water for 2 hours for rich broth.\n2. Boil eggs 6 min, cool, and peel.\n3. Marinate eggs in soy and mirin.\n4. Cook noodles.\n5. Mix broth with miso. Serve with noodles, egg, and nori.",
                            InstructionsSv = "1. Koka benen i vatten 2 timmar för en rik buljong.\n2. Koka äggen 6 min, kyl och skala.\n3. Marinera äggen i soja och mirin.\n4. Koka nudlarna.\n5. Blanda buljong med miso. Servera med nudlar, ägg och nori.",
                            Name = "Ramen",
                            PersonaTextEn = "I'm moody, soulful, and deep. The kind of love story that starts with hunger and ends with contentment. Soft egg optional but appreciated. Slurp responsibly.",
                            PersonaTextSv = "Jag är mörk, själfull och djup. Den typ av kärlekshistoria som börjar med hunger och slutar med tillfredsställelse. Mjukt ägg frivilligt men uppskattat.",
                            Tags = new[] { "Soup", "Noodles", "Broth", "Umami" }
                        },
                        new
                        {
                            Id = 11,
                            CookingTime = 45,
                            Cuisine = "Mexican",
                            Difficulty = "Medium",
                            ImageUrl = "https://images.unsplash.com/photo-1534352956036-cd81e27dd615?w=800",
                            IngredientsEn = "[{\"name\":\"Tortillas\",\"amount\":\"8\"},{\"name\":\"Chicken\",\"amount\":\"400 g\"},{\"name\":\"Enchilada sauce\",\"amount\":\"400 g\"},{\"name\":\"Cheddar\",\"amount\":\"200 g\"},{\"name\":\"Chipotle\",\"amount\":\"1 tbsp\"}]",
                            IngredientsSv = "[{\"namn\":\"Tortillas\",\"mängd\":\"8 st\"},{\"namn\":\"Kycklingkött\",\"mängd\":\"400 g\"},{\"namn\":\"Enchiladas-sås\",\"mängd\":\"400 g\"},{\"namn\":\"Cheddarost\",\"mängd\":\"200 g\"},{\"namn\":\"Chipotle\",\"mängd\":\"1 msk\"}]",
                            InstructionsEn = "1. Cook and shred the chicken.\n2. Mix chicken with half the cheese and chipotle.\n3. Fill tortillas and roll up.\n4. Place in baking dish, pour sauce over.\n5. Top with remaining cheese and bake 20 min at 200°C.",
                            InstructionsSv = "1. Koka och strimla kycklingen.\n2. Blanda kyckling med hälften av osten och chipotle.\n3. Fyll tortillas och rulla ihop.\n4. Lägg i ugnsform, häll sås över.\n5. Täck med resten av osten och grädda 20 min på 200°C.",
                            Name = "Enchiladas",
                            PersonaTextEn = "Wrapped up tight and full of surprises. I'm saucy, cheesy, and heat is my personality. Don't unwrap until you're ready for commitment.",
                            PersonaTextSv = "Tajt inrullad och full av överraskningar. Jag är sårande, ostaktig och hettan är min personlighet. Öppna inte förrän du är redo för åtaganden.",
                            Tags = new[] { "Cheese", "Spicy", "Saucy", "Comfort" }
                        },
                        new
                        {
                            Id = 12,
                            CookingTime = 40,
                            Cuisine = "Indian",
                            Difficulty = "Medium",
                            ImageUrl = "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800",
                            IngredientsEn = "[{\"name\":\"Chicken breast\",\"amount\":\"600 g\"},{\"name\":\"Crushed tomatoes\",\"amount\":\"400 g\"},{\"name\":\"Cream\",\"amount\":\"200 ml\"},{\"name\":\"Tikka masala spice\",\"amount\":\"3 tbsp\"},{\"name\":\"Onion\",\"amount\":\"1\"}]",
                            IngredientsSv = "[{\"namn\":\"Kycklingfilé\",\"mängd\":\"600 g\"},{\"namn\":\"Krossade tomater\",\"mängd\":\"400 g\"},{\"namn\":\"Grädde\",\"mängd\":\"200 ml\"},{\"namn\":\"Tikka masala-krydda\",\"mängd\":\"3 msk\"},{\"namn\":\"Lök\",\"mängd\":\"1 st\"}]",
                            InstructionsEn = "1. Marinate chicken in yoghurt and tikka spice.\n2. Grill chicken until charred.\n3. Sauté onion and garlic.\n4. Add tomatoes and spice, simmer 10 min.\n5. Add cream and chicken, simmer 10 min.",
                            InstructionsSv = "1. Marinera kyckling i yoghurt och tikka-krydda.\n2. Grilla kyckling tills brynt.\n3. Fräs lök och vitlök.\n4. Tillsätt tomater och krydda, koka 10 min.\n5. Tillsätt grädde och kyckling, koka 10 min.",
                            Name = "Tikka Masala",
                            PersonaTextEn = "Britain's favorite, born from love across cultures. I'm creamy, aromatic, and always a good idea. Naan is my wingman.",
                            PersonaTextSv = "Storbritanniens favorit, född av kärlek över kulturer. Jag är krämig, aromatisk och alltid en bra idé. Naan är min kompis.",
                            Tags = new[] { "Curry", "Creamy", "Aromatic", "Naan" }
                        },
                        new
                        {
                            Id = 13,
                            CookingTime = 60,
                            Cuisine = "Chinese",
                            Difficulty = "Medium",
                            ImageUrl = "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800",
                            IngredientsEn = "[{\"name\":\"Dumpling wrappers\",\"amount\":\"30\"},{\"name\":\"Ground pork\",\"amount\":\"300 g\"},{\"name\":\"Cabbage\",\"amount\":\"150 g\"},{\"name\":\"Ginger\",\"amount\":\"1 tbsp\"},{\"name\":\"Sesame oil\",\"amount\":\"1 tbsp\"}]",
                            IngredientsSv = "[{\"namn\":\"Dumplingsdegjbitar\",\"mängd\":\"30 st\"},{\"namn\":\"Fläskfärs\",\"mängd\":\"300 g\"},{\"namn\":\"Kål\",\"mängd\":\"150 g\"},{\"namn\":\"Ingefära\",\"mängd\":\"1 msk\"},{\"namn\":\"Sesamolja\",\"mängd\":\"1 msk\"}]",
                            InstructionsEn = "1. Mix ground pork with cabbage, ginger, and sesame oil.\n2. Place filling in center of each wrapper.\n3. Fold and crimp the edges.\n4. Steam for 8 min or pan-fry with a lid.",
                            InstructionsSv = "1. Blanda fläskfärs med kål, ingefära och sesamolja.\n2. Lägg fyllning i mitten av varje degbit.\n3. Vik och nyp ihop kanterna.\n4. Ånga 8 min eller stek i olja med lock.",
                            Name = "Dumplings",
                            PersonaTextEn = "Small, sweet, and full of secrets. I'm steamed, pan-fried, or both. Dip me in sauce and watch sparks fly. One bite, and you're mine.",
                            PersonaTextSv = "Liten, söt och full av hemligheter. Jag är ångad, stekt eller båda. Doppa mig i sås och se gnistorna flyga.",
                            Tags = new[] { "Steamed", "Pork", "Dipping Sauce", "Dim Sum" }
                        },
                        new
                        {
                            Id = 14,
                            CookingTime = 25,
                            Cuisine = "German",
                            Difficulty = "Medium",
                            ImageUrl = "https://images.unsplash.com/photo-1599921841143-819065a55cc6?w=800",
                            IngredientsEn = "[{\"name\":\"Pork cutlets\",\"amount\":\"4\"},{\"name\":\"Breadcrumbs\",\"amount\":\"100 g\"},{\"name\":\"Eggs\",\"amount\":\"2\"},{\"name\":\"Flour\",\"amount\":\"50 g\"},{\"name\":\"Butter\",\"amount\":\"4 tbsp\"}]",
                            IngredientsSv = "[{\"namn\":\"Fläskschnitzel\",\"mängd\":\"4 st\"},{\"namn\":\"Ströbröd\",\"mängd\":\"100 g\"},{\"namn\":\"Ägg\",\"mängd\":\"2 st\"},{\"namn\":\"Mjöl\",\"mängd\":\"50 g\"},{\"namn\":\"Smör\",\"mängd\":\"4 msk\"}]",
                            InstructionsEn = "1. Pound meat thin with a mallet.\n2. Bread in flour, egg, and breadcrumbs.\n3. Fry in butter on medium heat until golden.\n4. Serve with lemon and potatoes.",
                            InstructionsSv = "1. Banka köttet tunt med en köttklubba.\n2. Panera i mjöl, ägg och ströbröd.\n3. Stek i smör på medelhög värme tills gyllengul.\n4. Servera med citron och potatis.",
                            Name = "Schnitzel",
                            PersonaTextEn = "Crispy, golden, and no-nonsense. I'm the tall, dark stranger of the meat world. Hammered flat for maximum reach.",
                            PersonaTextSv = "Krispig, gyllene och rättfram. Jag är den mörka främlingen i köttvärlden. Bankad platt för maximal räckvidd.",
                            Tags = new[] { "Crispy", "Pork", "Breaded", "Classic" }
                        },
                        new
                        {
                            Id = 15,
                            CookingTime = 15,
                            Cuisine = "German",
                            Difficulty = "Easy",
                            ImageUrl = "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800",
                            IngredientsEn = "[{\"name\":\"Bratwurst\",\"amount\":\"4\"},{\"name\":\"Ketchup\",\"amount\":\"200 g\"},{\"name\":\"Curry powder\",\"amount\":\"3 tsp\"},{\"name\":\"Paprika\",\"amount\":\"1 tsp\"}]",
                            IngredientsSv = "[{\"namn\":\"Bratwurst\",\"mängd\":\"4 st\"},{\"namn\":\"Ketchup\",\"mängd\":\"200 g\"},{\"namn\":\"Currykrydda\",\"mängd\":\"3 tsk\"},{\"namn\":\"Paprikapulver\",\"mängd\":\"1 tsk\"}]",
                            InstructionsEn = "1. Grill or fry the bratwurst.\n2. Mix ketchup with curry powder and paprika.\n3. Slice the sausage.\n4. Pour sauce over. Serve with fries.",
                            InstructionsSv = "1. Grilla eller stek bratwursten.\n2. Blanda ketchup med currykrydda och paprika.\n3. Skär korven i bitar.\n4. Häll såsen över. Servera med pommes.",
                            Name = "Currywurst",
                            PersonaTextEn = "Berlin street food legend. I'm saucy, satisfying, and don't care about your plans. Curried sausage? More like curried feelings.",
                            PersonaTextSv = "Berlin-legend inom gatumat. Jag är sårande, tillfredsställande och bryr mig inte om dina planer. Currykryddad korv? Snarare currykryddade känslor.",
                            Tags = new[] { "Sausage", "Curry", "Street Food", "Berlin" }
                        },
                        new
                        {
                            Id = 16,
                            CookingTime = 30,
                            Cuisine = "Middle Eastern",
                            Difficulty = "Easy",
                            ImageUrl = "https://images.unsplash.com/photo-1593001872095-7d5b3868fb1d?w=800",
                            IngredientsEn = "[{\"name\":\"Chickpeas\",\"amount\":\"400 g\"},{\"name\":\"Cilantro\",\"amount\":\"1 bunch\"},{\"name\":\"Parsley\",\"amount\":\"1 bunch\"},{\"name\":\"Garlic\",\"amount\":\"3 cloves\"},{\"name\":\"Cumin\",\"amount\":\"2 tsp\"},{\"name\":\"Tahini\",\"amount\":\"3 tbsp\"}]",
                            IngredientsSv = "[{\"namn\":\"Kikärtor\",\"mängd\":\"400 g\"},{\"namn\":\"Koriander\",\"mängd\":\"1 knippe\"},{\"namn\":\"Persilja\",\"mängd\":\"1 knippe\"},{\"namn\":\"Vitlök\",\"mängd\":\"3 klyftor\"},{\"namn\":\"Spiskummin\",\"mängd\":\"2 tsk\"},{\"namn\":\"Tahini\",\"mängd\":\"3 msk\"}]",
                            InstructionsEn = "1. Coarsely blend chickpeas, herbs, garlic, and spices.\n2. Shape into balls.\n3. Deep fry at 180°C until golden.\n4. Serve in pita with tahini and salad.",
                            InstructionsSv = "1. Mixa kikärtor, örter, vitlök och kryddor grovt.\n2. Forma till bollar.\n3. Fritera i olja på 180°C tills gyllengula.\n4. Servera i pita med tahini och sallad.",
                            Name = "Falafel",
                            PersonaTextEn = "Crispy on the outside, herbaceous on the inside. I'm vegetarian but can seduce anyone. Tahini is my perfume.",
                            PersonaTextSv = "Knaprig utanpå, örtrik inuti. Jag är vegetarisk men kan förföra vem som helst. Tahini är min parfym.",
                            Tags = new[] { "Vegetarian", "Crispy", "Tahini", "Wrap" }
                        },
                        new
                        {
                            Id = 17,
                            CookingTime = 40,
                            Cuisine = "Korean",
                            Difficulty = "Medium",
                            ImageUrl = "https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=800",
                            IngredientsEn = "[{\"name\":\"Rice\",\"amount\":\"300 g\"},{\"name\":\"Beef\",\"amount\":\"200 g\"},{\"name\":\"Spinach\",\"amount\":\"100 g\"},{\"name\":\"Carrots\",\"amount\":\"2\"},{\"name\":\"Eggs\",\"amount\":\"4\"},{\"name\":\"Gochujang\",\"amount\":\"2 tbsp\"}]",
                            IngredientsSv = "[{\"namn\":\"Ris\",\"mängd\":\"300 g\"},{\"namn\":\"Nötkött\",\"mängd\":\"200 g\"},{\"namn\":\"Spenat\",\"mängd\":\"100 g\"},{\"namn\":\"Morötter\",\"mängd\":\"2 st\"},{\"namn\":\"Ägg\",\"mängd\":\"4 st\"},{\"namn\":\"Gochujang\",\"mängd\":\"2 msk\"}]",
                            InstructionsEn = "1. Cook the rice.\n2. Marinate and stir-fry beef in soy and sesame oil.\n3. Blanch spinach, stir-fry carrots.\n4. Fry eggs sunny side up.\n5. Arrange everything in bowl, top with egg and gochujang.",
                            InstructionsSv = "1. Koka riset.\n2. Marinera och stek nötköttet i soja och sesamolja.\n3. Blanchera spenat, stek morötter.\n4. Stek ägg med rinnande gula.\n5. Lägg allt i skål, toppa med ägg och gochujang.",
                            Name = "Bibimbap",
                            PersonaTextEn = "Colorful, creative, and mixed for a reason. I'm everything in one bowl — sweet, spicy, savory, fresh. Put your egg on top and watch magic happen.",
                            PersonaTextSv = "Färgglad, kreativ och blandad med anledning. Jag är allt i en skål. Lägg ditt ägg på toppen och se magi hända.",
                            Tags = new[] { "Rice", "Korean", "Spicy", "Colorful" }
                        },
                        new
                        {
                            Id = 18,
                            CookingTime = 90,
                            Cuisine = "Italian",
                            Difficulty = "Hard",
                            ImageUrl = "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800",
                            IngredientsEn = "[{\"name\":\"Lasagna sheets\",\"amount\":\"12\"},{\"name\":\"Ground beef\",\"amount\":\"500 g\"},{\"name\":\"Crushed tomatoes\",\"amount\":\"400 g\"},{\"name\":\"Béchamel sauce\",\"amount\":\"500 ml\"},{\"name\":\"Parmesan\",\"amount\":\"100 g\"}]",
                            IngredientsSv = "[{\"namn\":\"Lasagneplattor\",\"mängd\":\"12 st\"},{\"namn\":\"Nötfärs\",\"mängd\":\"500 g\"},{\"namn\":\"Krossade tomater\",\"mängd\":\"400 g\"},{\"namn\":\"Béchamelsås\",\"mängd\":\"500 ml\"},{\"namn\":\"Parmesanost\",\"mängd\":\"100 g\"}]",
                            InstructionsEn = "1. Make the meat sauce with onion, tomato, and beef.\n2. Make béchamel sauce.\n3. Layer lasagna sheets, meat sauce, and béchamel.\n4. Top with parmesan.\n5. Bake 40 min at 180°C.",
                            InstructionsSv = "1. Gör köttfärssåsen med lök, tomat och köttfärs.\n2. Gör béchamelsås.\n3. Varva lasagneplattor, köttfärssås och béchamel.\n4. Toppa med parmesan.\n5. Grädda 40 min på 180°C.",
                            Name = "Lasagna",
                            PersonaTextEn = "Layers. Every one of them meaningful. I'm patient, rich, and worth every minute. No shortcuts, no substitutes.",
                            PersonaTextSv = "Lager. Varje ett av dem meningsfullt. Jag är tålmodig, rik och värd varje minut. Inga genvägar, inga substitut.",
                            Tags = new[] { "Pasta", "Baked", "Layers", "Comfort" }
                        },
                        new
                        {
                            Id = 19,
                            CookingTime = 40,
                            Cuisine = "American",
                            Difficulty = "Easy",
                            ImageUrl = "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800",
                            IngredientsEn = "[{\"name\":\"Chicken wings\",\"amount\":\"1 kg\"},{\"name\":\"Buffalo sauce\",\"amount\":\"100 ml\"},{\"name\":\"Butter\",\"amount\":\"50 g\"},{\"name\":\"Garlic\",\"amount\":\"2 cloves\"},{\"name\":\"Salt\",\"amount\":\"1 tsp\"}]",
                            IngredientsSv = "[{\"namn\":\"Kycklingvingar\",\"mängd\":\"1 kg\"},{\"namn\":\"Buffalosås\",\"mängd\":\"100 ml\"},{\"namn\":\"Smör\",\"mängd\":\"50 g\"},{\"namn\":\"Vitlök\",\"mängd\":\"2 klyftor\"},{\"namn\":\"Salt\",\"mängd\":\"1 tsk\"}]",
                            InstructionsEn = "1. Pat wings dry and season with salt.\n2. Bake at 220°C for 35-40 min, flipping halfway.\n3. Melt butter with buffalo sauce and garlic.\n4. Toss hot wings in the sauce.",
                            InstructionsSv = "1. Torka vingarna och krydda med salt.\n2. Grädda på 220°C i 35-40 min, vänd halvvägs.\n3. Smält smör med buffalosås och vitlök.\n4. Slå såsen över de heta vingarna.",
                            Name = "Chicken Wings",
                            PersonaTextEn = "Messy, addictive, and always the life of the party. Buffalo is my middle name. Sauce everywhere, joy in my heart.",
                            PersonaTextSv = "Stökig, beroendeframkallande och alltid festens stjärna. Buffalo är mitt mellannamn. Sås överallt, glädje i hjärtat.",
                            Tags = new[] { "Chicken", "Buffalo", "Crispy", "Party" }
                        },
                        new
                        {
                            Id = 20,
                            CookingTime = 15,
                            Cuisine = "Hawaiian",
                            Difficulty = "Easy",
                            ImageUrl = "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800",
                            IngredientsEn = "[{\"name\":\"Sushi rice\",\"amount\":\"300 g\"},{\"name\":\"Sashimi tuna\",\"amount\":\"200 g\"},{\"name\":\"Avocado\",\"amount\":\"1\"},{\"name\":\"Edamame\",\"amount\":\"100 g\"},{\"name\":\"Soy sauce\",\"amount\":\"3 tbsp\"},{\"name\":\"Sesame seeds\",\"amount\":\"2 tsp\"}]",
                            IngredientsSv = "[{\"namn\":\"Sushiris\",\"mängd\":\"300 g\"},{\"namn\":\"Tonfisk sashimikvalitet\",\"mängd\":\"200 g\"},{\"namn\":\"Avokado\",\"mängd\":\"1 st\"},{\"namn\":\"Edamame\",\"mängd\":\"100 g\"},{\"namn\":\"Sojasamn\",\"mängd\":\"3 msk\"},{\"namn\":\"Sesamfrön\",\"mängd\":\"2 tsk\"}]",
                            InstructionsEn = "1. Cook the rice.\n2. Cube tuna, marinate in soy and sesame oil.\n3. Slice avocado.\n4. Build bowl with rice, tuna, avocado, and edamame.\n5. Top with sesame seeds and sweet soy.",
                            InstructionsSv = "1. Koka riset.\n2. Skär tonfisken i kuber, marinera i soja och sesamolja.\n3. Skiva avokado.\n4. Bygg skålen med ris, tonfisk, avokado och edamame.\n5. Toppa med sesamfrön och söt soja.",
                            Name = "Poke Bowl",
                            PersonaTextEn = "Fresh, cool, and low-key romantic. I'm the slow Sunday morning of food. Ahi tuna, rice, and vibes. No cooking required, just vibes.",
                            PersonaTextSv = "Fräsch, cool och lite romantisk. Jag är matens lugna söndagsmorgon. Ahi tuna, ris och stämning. Ingen matlagning krävs.",
                            Tags = new[] { "Rice", "Tuna", "Fresh", "Healthy" }
                        },
                        new
                        {
                            Id = 21,
                            CookingTime = 30,
                            Cuisine = "Swedish",
                            Difficulty = "Easy",
                            ImageUrl = "https://images.unsplash.com/photo-1529543544282-ea669407fca3?w=800",
                            IngredientsEn = "[{\"name\":\"Ground beef\",\"amount\":\"500 g\"},{\"name\":\"Onion\",\"amount\":\"1\"},{\"name\":\"Egg\",\"amount\":\"1\"},{\"name\":\"Breadcrumbs\",\"amount\":\"3 tbsp\"},{\"name\":\"Lingonberry jam\",\"amount\":\"100 g\"},{\"name\":\"Cream\",\"amount\":\"200 ml\"}]",
                            IngredientsSv = "[{\"namn\":\"Nötfärs\",\"mängd\":\"500 g\"},{\"namn\":\"Lök\",\"mängd\":\"1 st\"},{\"namn\":\"Ägg\",\"mängd\":\"1 st\"},{\"namn\":\"Ströbröd\",\"mängd\":\"3 msk\"},{\"namn\":\"Lingonsylt\",\"mängd\":\"100 g\"},{\"namn\":\"Grädde\",\"mängd\":\"200 ml\"}]",
                            InstructionsEn = "1. Mix ground beef with chopped onion, egg, and breadcrumbs.\n2. Roll into even balls.\n3. Fry in butter until cooked through.\n4. Make cream sauce in the same pan.\n5. Serve with mashed potatoes and lingonberry jam.",
                            InstructionsSv = "1. Blanda färsen med hackad lök, ägg och ströbröd.\n2. Rulla till jämna bollar.\n3. Stek i smör tills genomstekta.\n4. Gör gräddsås i pannan.\n5. Servera med potatismos och lingonsylt.",
                            Name = "Köttbullar",
                            PersonaTextEn = "Meaty, comforting, and ready to mingle with lingonberry. I'm the IKEA trip you didn't know you needed.",
                            PersonaTextSv = "Köttiga, trygga och redo att umgås med lingonsylt. Jag är IKEA-resan du inte visste att du behövde.",
                            Tags = new[] { "Swedish", "Beef", "Lingonberry", "Comfort" }
                        },
                        new
                        {
                            Id = 22,
                            CookingTime = 60,
                            Cuisine = "Swedish",
                            Difficulty = "Medium",
                            ImageUrl = "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800",
                            IngredientsEn = "[{\"name\":\"Sandwich bread\",\"amount\":\"1 loaf\"},{\"name\":\"Shrimp\",\"amount\":\"200 g\"},{\"name\":\"Salmon\",\"amount\":\"150 g\"},{\"name\":\"Mayonnaise\",\"amount\":\"200 g\"},{\"name\":\"Cream\",\"amount\":\"200 ml\"},{\"name\":\"Cucumber\",\"amount\":\"1\"}]",
                            IngredientsSv = "[{\"namn\":\"Formbröd\",\"mängd\":\"1 limpa\"},{\"namn\":\"Räkor\",\"mängd\":\"200 g\"},{\"namn\":\"Lax\",\"mängd\":\"150 g\"},{\"namn\":\"Majonnäs\",\"mängd\":\"200 g\"},{\"namn\":\"Grädde\",\"mängd\":\"200 ml\"},{\"namn\":\"Gurka\",\"mängd\":\"1 st\"}]",
                            InstructionsEn = "1. Slice bread into layers.\n2. Mix fillings with mayonnaise.\n3. Spread filling between bread layers.\n4. Whip cream and cover the outside.\n5. Decorate with shrimp, salmon, and cucumber.",
                            InstructionsSv = "1. Skär brödet i lager.\n2. Blanda fyllningar med majonnäs.\n3. Bred fyllning mellan brödlagren.\n4. Vispa grädden och täck utsidan.\n5. Dekorera med räkor, lax och gurka.",
                            Name = "Smörgåstårta",
                            PersonaTextEn = "Layers of bread, fillings, and mayo magic. I'm the sandwich cake that questions your diet. Made for birthdays and summer lunches.",
                            PersonaTextSv = "Lager av bröd, fyllningar och majonnäsmagi. Jag är smörgåstårtan som ifrågasätter din diet. Gjord för kalas och sommarluncher.",
                            Tags = new[] { "Swedish", "Sandwich", "Mayonnaise", "Party" }
                        },
                        new
                        {
                            Id = 23,
                            CookingTime = 60,
                            Cuisine = "Swedish",
                            Difficulty = "Easy",
                            ImageUrl = "https://images.unsplash.com/photo-1529543544282-ea669407fca3?w=800",
                            IngredientsEn = "[{\"name\":\"Ground beef\",\"amount\":\"600 g\"},{\"name\":\"Eggs\",\"amount\":\"2\"},{\"name\":\"Onion\",\"amount\":\"1\"},{\"name\":\"Milk\",\"amount\":\"100 ml\"},{\"name\":\"Breadcrumbs\",\"amount\":\"4 tbsp\"},{\"name\":\"Lingonberry jam\",\"amount\":\"100 g\"}]",
                            IngredientsSv = "[{\"namn\":\"Nötfärs\",\"mängd\":\"600 g\"},{\"namn\":\"Ägg\",\"mängd\":\"2 st\"},{\"namn\":\"Lök\",\"mängd\":\"1 st\"},{\"namn\":\"Mjölk\",\"mängd\":\"100 ml\"},{\"namn\":\"Ströbröd\",\"mängd\":\"4 msk\"},{\"namn\":\"Lingonsylt\",\"mängd\":\"100 g\"}]",
                            InstructionsEn = "1. Mix all ingredients except lingonberry jam.\n2. Shape into a loaf in a baking dish.\n3. Bake at 175°C for 50-60 min.\n4. Serve with mashed potatoes and lingonberry jam.",
                            InstructionsSv = "1. Blanda alla ingredienser utom lingonsylt.\n2. Forma en limpa i en ugnsform.\n3. Grädda på 175°C i 50-60 min.\n4. Servera med potatismos och lingonsylt.",
                            Name = "Köttfarslimpa",
                            PersonaTextEn = "Swedish meatloaf — cozy, reliable, and always there for you. Lingonberry on the side, no questions asked.",
                            PersonaTextSv = "Svensk köttfarslimpa — mysig, pålitlig och alltid där för dig. Lingonsylt på sidan, inga frågor.",
                            Tags = new[] { "Swedish", "Meatloaf", "Comfort", "Lingonberry" }
                        },
                        new
                        {
                            Id = 24,
                            CookingTime = 20,
                            Cuisine = "Swedish",
                            Difficulty = "Easy",
                            ImageUrl = "https://images.unsplash.com/photo-1518779578993-ec3579fee39f?w=800",
                            IngredientsEn = "[{\"name\":\"Potatoes\",\"amount\":\"400 g\"},{\"name\":\"Ground beef or sausage\",\"amount\":\"300 g\"},{\"name\":\"Onion\",\"amount\":\"1\"},{\"name\":\"Eggs\",\"amount\":\"4\"},{\"name\":\"Pickled beets\",\"amount\":\"100 g\"}]",
                            IngredientsSv = "[{\"namn\":\"Potatis\",\"mängd\":\"400 g\"},{\"namn\":\"Köttfärs eller korv\",\"mängd\":\"300 g\"},{\"namn\":\"Lök\",\"mängd\":\"1 st\"},{\"namn\":\"Ägg\",\"mängd\":\"4 st\"},{\"namn\":\"Inlagda rödbetor\",\"mängd\":\"100 g\"}]",
                            InstructionsEn = "1. Boil and dice the potatoes.\n2. Fry potatoes and onion in butter until golden.\n3. Add meat, fry until cooked through.\n4. Fry eggs separately.\n5. Serve with egg on top and beets on the side.",
                            InstructionsSv = "1. Koka och tärna potatisen.\n2. Stek potatis och lök i smör tills gyllengula.\n3. Tillsätt köttet, stek tills genomstekt.\n4. Stek äggen separat.\n5. Servera med ägg ovanpå och rödbetor på sidan.",
                            Name = "Pytt i Panna",
                            PersonaTextEn = "Cube-shaped comfort in a pan. I'm potatoes and history — best with a fried egg on top and pickled beets.",
                            PersonaTextSv = "Kubformad tröst i en panna. Jag är potatis och historia — bäst med stekt ägg ovanpå och inlagda rödbetor.",
                            Tags = new[] { "Swedish", "Potatoes", "Pan", "Retro" }
                        },
                        new
                        {
                            Id = 25,
                            CookingTime = 45,
                            Cuisine = "Chinese",
                            Difficulty = "Medium",
                            ImageUrl = "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=800",
                            IngredientsEn = "[{\"name\":\"Wonton wrappers\",\"amount\":\"24\"},{\"name\":\"Ground pork\",\"amount\":\"200 g\"},{\"name\":\"Shrimp\",\"amount\":\"100 g\"},{\"name\":\"Chicken broth\",\"amount\":\"1 liter\"},{\"name\":\"Ginger\",\"amount\":\"1 tbsp\"},{\"name\":\"Spring onion\",\"amount\":\"2\"}]",
                            IngredientsSv = "[{\"namn\":\"Wontonskinn\",\"mängd\":\"24 st\"},{\"namn\":\"Fläskfärs\",\"mängd\":\"200 g\"},{\"namn\":\"Räkor\",\"mängd\":\"100 g\"},{\"namn\":\"Kycklingbuljong\",\"mängd\":\"1 liter\"},{\"namn\":\"Ingefära\",\"mängd\":\"1 msk\"},{\"namn\":\"Salladslök\",\"mängd\":\"2 st\"}]",
                            InstructionsEn = "1. Mix ground pork with chopped shrimp, ginger, and soy.\n2. Place filling in each wrapper and fold.\n3. Bring chicken broth to boil with ginger.\n4. Cook wontons in broth for 4-5 min.\n5. Serve garnished with spring onion.",
                            InstructionsSv = "1. Blanda fläskfärs med hackade räkor, ingefära och soja.\n2. Lägg fyllning i varje wontonskinn och vik ihop.\n3. Koka kycklingbuljong med ingefära.\n4. Koka wontons i buljongen 4-5 min.\n5. Servera garnerat med salladslök.",
                            Name = "Wonton Soup",
                            PersonaTextEn = "Delicate, warming, and surprisingly deep. My wontons hold secrets. One spoonful and you're home.",
                            PersonaTextSv = "Delikat, värmande och förvånansvärt djup. Mina wontons håller hemligheter. En sked och du är hemma.",
                            Tags = new[] { "Soup", "Dumplings", "Broth", "Comfort" }
                        });
                });

            modelBuilder.Entity("Biine.API.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cuisine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleMapsUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GooglePlaceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Lat")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Lng")
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PriceLevel")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("Biine.API.Models.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextSv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Translations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "onboarding.title",
                            TextEn = "What are you craving?",
                            TextSv = "Vad är du sugen på?"
                        },
                        new
                        {
                            Id = 2,
                            Key = "onboarding.subtitle",
                            TextEn = "Swipe to find your match",
                            TextSv = "Svajpa för att hitta din match"
                        },
                        new
                        {
                            Id = 3,
                            Key = "onboarding.start",
                            TextEn = "Start",
                            TextSv = "Starta"
                        },
                        new
                        {
                            Id = 4,
                            Key = "swipe.like",
                            TextEn = "Like",
                            TextSv = "Gillar"
                        },
                        new
                        {
                            Id = 5,
                            Key = "swipe.dislike",
                            TextEn = "Not today",
                            TextSv = "Inte idag"
                        },
                        new
                        {
                            Id = 6,
                            Key = "swipe.empty",
                            TextEn = "You've seen it all! Pull down to restart.",
                            TextSv = "Du har sett allt! Dra nedåt för att börja om."
                        },
                        new
                        {
                            Id = 7,
                            Key = "match.title",
                            TextEn = "It's a match!",
                            TextSv = "Det är en match!"
                        },
                        new
                        {
                            Id = 8,
                            Key = "match.subtitle",
                            TextEn = "What would you like to do?",
                            TextSv = "Vad vill du göra?"
                        },
                        new
                        {
                            Id = 9,
                            Key = "match.cook",
                            TextEn = "Cook at home",
                            TextSv = "Laga hemma"
                        },
                        new
                        {
                            Id = 10,
                            Key = "match.restaurant",
                            TextEn = "Find a restaurant",
                            TextSv = "Hitta restaurang"
                        },
                        new
                        {
                            Id = 11,
                            Key = "match.skip",
                            TextEn = "Keep swiping",
                            TextSv = "Fortsätt svajpa"
                        },
                        new
                        {
                            Id = 12,
                            Key = "recipe.ingredients",
                            TextEn = "Ingredients",
                            TextSv = "Ingredienser"
                        },
                        new
                        {
                            Id = 13,
                            Key = "recipe.instructions",
                            TextEn = "Instructions",
                            TextSv = "Instruktioner"
                        },
                        new
                        {
                            Id = 14,
                            Key = "recipe.cookingTime",
                            TextEn = "Cooking time",
                            TextSv = "Tillagningstid"
                        },
                        new
                        {
                            Id = 15,
                            Key = "recipe.difficulty",
                            TextEn = "Difficulty",
                            TextSv = "Svårighetsgrad"
                        },
                        new
                        {
                            Id = 16,
                            Key = "recipe.difficulty.easy",
                            TextEn = "Easy",
                            TextSv = "Lätt"
                        },
                        new
                        {
                            Id = 17,
                            Key = "recipe.difficulty.medium",
                            TextEn = "Medium",
                            TextSv = "Medel"
                        },
                        new
                        {
                            Id = 18,
                            Key = "recipe.difficulty.hard",
                            TextEn = "Hard",
                            TextSv = "Svår"
                        },
                        new
                        {
                            Id = 19,
                            Key = "recipe.minutes",
                            TextEn = "min",
                            TextSv = "min"
                        },
                        new
                        {
                            Id = 20,
                            Key = "restaurant.title",
                            TextEn = "Nearby restaurants",
                            TextSv = "Restauranger i närheten"
                        },
                        new
                        {
                            Id = 21,
                            Key = "restaurant.noResults",
                            TextEn = "No restaurants found",
                            TextSv = "Inga restauranger hittades"
                        },
                        new
                        {
                            Id = 22,
                            Key = "restaurant.open",
                            TextEn = "Open now",
                            TextSv = "Öppet nu"
                        },
                        new
                        {
                            Id = 23,
                            Key = "restaurant.closed",
                            TextEn = "Closed",
                            TextSv = "Stängt"
                        },
                        new
                        {
                            Id = 24,
                            Key = "error.network",
                            TextEn = "Something went wrong. Please try again.",
                            TextSv = "Något gick fel. Försök igen."
                        },
                        new
                        {
                            Id = 25,
                            Key = "error.rateLimit",
                            TextEn = "Slow down! Wait a moment.",
                            TextSv = "Lugna dig lite! Vänta en stund."
                        },
                        new
                        {
                            Id = 26,
                            Key = "error.noSession",
                            TextEn = "Session expired. Reloading...",
                            TextSv = "Sessionen gick ut. Laddar om..."
                        },
                        new
                        {
                            Id = 27,
                            Key = "lang.switch",
                            TextEn = "Svenska",
                            TextSv = "English"
                        },
                        new
                        {
                            Id = 28,
                            Key = "app.tagline",
                            TextEn = "Find your food match",
                            TextSv = "Hitta din matmatch"
                        });
                });

            modelBuilder.Entity("Biine.API.Models.Interaction", b =>
                {
                    b.HasOne("Biine.API.Models.Recipe", "Recipe")
                        .WithMany("Interactions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Biine.API.Models.Recipe", b =>
                {
                    b.Navigation("Interactions");
                });
#pragma warning restore 612, 618
        }
    }
}
